End to End Agriculture Demo
digidotcom/xbee-micropython pull request #60
Opened 2020-12-17 12:13 UTC by rubenmoral

Commits will be squashed when merging into `master`.

2020-12-17 15:26 UTC, mikewadsten requested changes

2020-12-17 15:26 UTC, mikewadsten commented on samples/demos/end_to_end_agriculture/main.py
> +    for prop in xbee_properties:
```python
for prop, atcmd in xbee_properties.items():
```

2020-12-17 15:26 UTC, mikewadsten commented on samples/demos/end_to_end_agriculture/main.py
> +    if PROP_PASS not in properties or properties[PROP_PASS] is None:
Would this be a bit more succinct?

```python
if properties.get(PROP_PASS) is None:
```

2021-01-25 11:28 UTC, diescalo approved these changes

2021-01-25 11:39 UTC, merged